# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  version: '0.1.0-preview-$(Build.BuildNumber)'

steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: 'Extensions.DependencyInjection.AttributeModel/
Extensions.DependencyInjection.AttributeModel.csproj'
  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
      projects: '
Extensions.DependencyInjection.AttributeModel.Tests/Extensions.DependencyInjection.AttributeModel.Tests.csproj'
  - task: DotNetCoreCLI@2
    inputs:
      command: 'push'
      packagesToPush: '.artifacts/**.nupkg'
      nuGetFeedType: 'internal'
      publishVstsFeed: '6229c47b-407d-4664-8a80-cd1c29ee6834/78471781-20d7-4e3b-b03d-a21a9400d914'