name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    #- name: setup azure artifacts 
    #  run: wget -qO- https://aka.ms/install-artifacts-credprovider.sh | bash
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Push Nupkg to nuget.org
      #env: 
      #  VSS_NUGET_EXTERNAL_FEED_ENDPOINTS: ${{ secrets.NUGET_ORG }}
      run: dotnet nuget push --source "https://api.nuget.org/v3/index.json" --api-key ${{ secrets.NUGET_ORG }} "./.artifacts/*.nupkg" --skip-duplicate